spring:
  application:
    name: MVC_Meganet


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 56cbtm1b
    url: jdbc:mysql://localhost:3306/meganet_db

  jpa:
    hibernate:
      ddl-auto:
    show-sql: true

#
#logging:
#  level:
#    root: info
#    org.example.mvc_applicationforconnection.controller.StatementController: error
#  file:
#    name: logs/app.log

server:
  port: 8090
#spring.application.name=MVC_ApplicationForConnectionApplication
#spring.datasource.username=root
#spring.datasource.password=56cbtm1b
#spring.datasource.url=jdbc:mysql://localhost:3306/meganet_db
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.data.jdbc.dialect=mysql

#server.port=8181